src/apps/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from src.apps.core.views import CoreIndexView


urlpatterns = patterns('src.apps.core.views',

    url(r'', CoreIndexView.as_view(), name='index'),

)

src/apps/dashboard/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from src.apps.dashboard.views import DashboardIndexView, EffectLogWrite


urlpatterns = patterns('src.apps.dashboard.views',

    url(r'^accounts/profile/', DashboardIndexView.as_view(), name='dashboard_index'),
    url(r'accounts/write/$', EffectLogWrite.as_view(), name='effect_log_write'),

)

src/apps/effect_log/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from src.apps.effect_log.views import EffectLogIndexView, EffectLogList


urlpatterns = patterns('src.apps.effect_log.views',

    url(r'^index/', EffectLogIndexView.as_view(), name='effect_log_index'),
    url(r'^(?P<slug>[^/]+)/$', EffectLogList.as_view(), name='effect_log_in_category'),

)

src/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),

    url(r'^effect_log/', include('src.apps.effect_log.urls', namespace='effect_log')),
    url(r'^dashboard/', include('src.apps.dashboard.urls', namespace='dashboard')),
    url(r'^', include('src.apps.core.urls', namespace='core')),

]

src/apps/effect_log/models.py
# -*- coding: utf-8 -*-
import os
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
import mptt
from mptt.models import MPTTModel, TreeForeignKey
from autoslug import AutoSlugField
from autoslug.settings import slugify as default_slugify


def custom_slugify(value):
    # для перевода в кирилицу нужно установить pytils==0.3
    return default_slugify(value).replace('-', '_')


class Category(MPTTModel):
    """
    Description models
    """
    parent = TreeForeignKey(u'self', verbose_name='Parent', blank=True, null=True, related_name=u'children')
    user_name = models.ForeignKey(User, related_name='+', to_field=u"username")
    name = models.CharField(verbose_name='Name', max_length=255, db_index=True)
    description = models.TextField(verbose_name='Description', blank=True)
    slug = AutoSlugField(populate_from='name', slugify=custom_slugify, unique=True)
    date_created = models.DateTimeField(verbose_name="Date created", auto_now_add=True)
    is_active = models.BooleanField(verbose_name='Is active', default=None)

    class Meta:
        ordering = ['-date_created']
        verbose_name = u'Категория'
        verbose_name_plural = u'Категория'

    class MPTTMeta:
        order_insertion_by = ['name']
        level_attr = 'level'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('effect_log:category', args=[self.slug])

mptt.register(Category)

class EffectLog(models.Model):
    """
    Журнал эффективности
    """
    TECHNICAL, OPERATOR, PROIZVODSTVO = u'Технический простой', u'Простой по вине оператора', u'Производственный простой'
    STRUCTURE_CHOICES = (
        (TECHNICAL, u'Технический простой'),
        (OPERATOR, u'Простой по вине оператора'),
        (PROIZVODSTVO, u'Производственный простой')
    )
    category = TreeForeignKey(Category, verbose_name='Category', related_name='entries',)
    user_name = models.ForeignKey(User, related_name='+', to_field=u"username")
    operator = models.CharField(verbose_name='Operator', max_length=20)
    type_prostoy = models.CharField(verbose_name="Type Prostoya", max_length=40, choices=STRUCTURE_CHOICES, default=TECHNICAL)
    time_prostoy = models.TimeField(verbose_name='Time Prostoya')
    dlitelnost_prostoya = models.IntegerField(verbose_name=' Dlitelnost prostoya')
    comments = models.TextField(verbose_name='Comments')
    date_created = models.DateTimeField(verbose_name="Date created", auto_now_add=True)

    class Meta:
        ordering = ['-date_created']
        verbose_name = u'Журнал эффективности'
        verbose_name_plural = u'Журнал эффективности'

    def get_absolute_url(self):
        return reverse('core:index', args=[str(self.pk)])

src/apps/dashboard/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm, ModelChoiceField
from django import forms
from itertools import groupby
from operator import attrgetter
import mptt

from src.apps.effect_log.models import EffectLog, Category


class SelectCategory(ModelChoiceField):
    def __init__(self, *args, **kwargs):
        super(SelectCategory, self).__init__(*args, **kwargs)

        # фильтрация по полю 'description'.для внесение новых пунктов требуется перезапустить сервер
        groups = groupby(kwargs['queryset'], attrgetter('description'))

        self.choices = [(continent, [(c.id, self.label_from_instance(c)) for c in countries])
                        for continent, countries in groups]


class BaseFields(forms.Form):

    category = SelectCategory(queryset=Category.objects.exclude(level=0),
                              label=u'Категория',)


"""
class adds products in dashboard
"""

class EffectLogForm(ModelForm, BaseFields):
    class Meta:
        model = EffectLog
        fields = 'category','operator','type_prostoy','time_prostoy','dlitelnost_prostoya','comments',

src/apps/core/views.py
# -*- coding: utf-8 -*-
from django.views.generic import DetailView, TemplateView, ListView
from django.shortcuts import get_object_or_404, redirect


"""
Index page
"""
class CoreIndexView(TemplateView):
    template_name = 'apps/core/index.html'

src/apps/dashboard/views.py
# -*- coding: utf-8 -*-
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, BaseFormView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect

from src.apps.effect_log.models import EffectLog
from src.apps.dashboard.forms import EffectLogForm

"""
Index page Dashboard
"""
class DashboardIndexView(TemplateView):
    template_name = 'apps/dashboard/profile.html'
    model = EffectLog

    # Для вывода обьявлений определенного юзера
    def get(self, request, *args, **kwargs):
        kwargs['object_list'] = EffectLog.objects.filter(user_name_id=request.user)
        return super(DashboardIndexView, self).get(request, *args, **kwargs)


class EffectLogWrite(CreateView):
    template_name = 'apps/dashboard/add_log.html'
    model = EffectLog
    form_class = EffectLogForm

    def form_valid(self, form):
        form = EffectLogForm(self.request.POST, self.request.FILES)
        add = form.save(commit=False)
        add.user_name_id = self.request.user
        add.save()
        return redirect('dashboard:dashboard_index')

src/apps/effect_log/views.py
# -*- coding: utf-8 -*-
from django.views.generic import DetailView, TemplateView, ListView
from django.shortcuts import get_object_or_404, redirect

from src.apps.effect_log.models import Category, EffectLog


"""
Index page
"""
class EffectLogIndexView(ListView):
    template_name = 'apps/effect_log/effect_index.html'
    model = EffectLog

    def get_queryset(self):
        return EffectLog.objects.all()

class EffectLogList(ListView):
    template_name = 'apps/effect_log/effect_log_in_category.html'
    model = EffectLog
    context_object_name = 'log_vivod'

    def get_queryset(self):
        category = get_object_or_404(Category, slug=self.kwargs['slug'])

        # filter product in child category
        if category.is_child_node():
            return EffectLog.objects.filter(category_id=category.pk)
        # view all product in root category
        elif category.is_root_node():
            q = category.get_children()
            t = q.values('id')
            x = [item['id'] for item in t]
            return EffectLog.objects.filter(category_id__in=x)

src/templates/apps/core/index.html
{% extends "base.html" %}
{% load i18n static %}

{% block content %}

стартовая страница


{% endblock %}

src/templates/apps/dashboard/add_log.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
{% if user.is_authenticated %}

<div class="form-horizontal" role="form">
<form role="form" method="post" enctype="multipart/form-data" action=".">
  {% csrf_token %}
  {{ form|crispy }}

  <input class="btn btn-success col-sm-4" type="submit" value="{% trans 'Submit' %}" />
</form>
</div>


{% else %}
{% endif %}
{% endblock %}

src/templates/apps/dashboard/log_in_dashboard.html
 <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Дата внесения лога</th>
                  <th>Оператор</th>
                  <th>Тип простоя</th>
                  <th>Время фиксации простоя</th>
                  <th>Длительность простоя</th>
                  <th>Комментарии оператора</th>
                  <th>Ф.И.О</th>
                </tr>
              </thead>
              <tbody>
     {% for log_vivod in object_list %}
<tr>


      {% include "apps/effect_log/effect_log.html" %}

</tr>
                {% endfor %}
              </tbody>
            </table>
          </div>

src/templates/apps/dashboard/profile.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    {% if user.is_authenticated %}

        <h2 class="col-lg-push-7">Личный кабинет  {{ user.username }} 'a</h2>
        <a href="{% url 'dashboard:effect_log_write' %}">Добавить запись</a>


        {% include "apps/dashboard/log_in_dashboard.html" %}

    {% endif %}

{% endblock %}

src/templates/apps/effect_log/effect_index.html
{% extends "base_effect.html" %}
{% load i18n static %}

{% block content %}

    <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Дата внесения лога</th>
                  <th>Оператор</th>
                  <th>Тип простоя</th>
                  <th>Время фиксации простоя</th>
                  <th>Длительность простоя</th>
                  <th>Комментарии оператора</th>
                  <th>Ф.И.О</th>
                </tr>
              </thead>
              <tbody>

              {% for log_vivod in object_list %}
                <tr>

      {% include "apps/effect_log/effect_log.html" %}


                </tr>
              {% endfor %}

              </tbody>
            </table>
          </div>


{% endblock %}

src/templates/apps/effect_log/effect_log.html
<td>{{ log_vivod.id }}</td>
<td>{{ log_vivod.date_created }}</td>
<td>{{ log_vivod.operator }}</td>
<td>{{ log_vivod.type_prostoy }}</td>
<td>{{ log_vivod.time_prostoy }}</td>
<td>{{ log_vivod.dlitelnost_prostoya }}</td>
<td>{{ log_vivod.comments }}</td>
<td>{{ log_vivod.user_name }}</td>

src/templates/apps/effect_log/effect_log_in_category.html
{% extends "base_effect.html" %}
{% load i18n static %}

{% block content %}
    <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Дата внесения лога</th>
                  <th>Оператор</th>
                  <th>Тип простоя</th>
                  <th>Время фиксации простоя</th>
                  <th>Длительность простоя</th>
                  <th>Комментарии оператора</th>
                  <th>Ф.И.О</th>
                </tr>
              </thead>
              <tbody>
     {% for log_vivod in object_list %}
<tr>

      {% include "apps/effect_log/effect_log.html" %}

</tr>
                {% endfor %}
              </tbody>
            </table>
          </div>





{% endblock %}

src/templates/apps/effect_log/inclusion/categories_list.html
{% load i18n static %}
{% load mptt_tags %}



{% full_tree_for_model effect_log.Category as categories  %}
{% for node,structure in categories|tree_info %}

    {% if structure.new_level %}<ul class="nav nav-sidebar"><li>{% endif %}
    {% ifequal node categories %}
        <a class="" href="/effect_log/{{ node.slug }}/">{{ node.name }}</a>
    {% else %}
        <a class="" href="/effect_log/{{ node.slug }}/">{{ node.name }}</a>
        {% ifequal node.parent_id categories.pk %}{% endifequal %}
    {% endifequal %}
    {% for level in structure.closed_levels %}</li></ul>{% endfor %}
{% endfor %}

src/templates/base.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PPR</title>

    <!-- Bootstrap -->
    {% load i18n %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href='{% static "bootstrap/css/bootstrap.min.css" %}' />
    <link rel="stylesheet" type="text/css" href='{% static "bootstrap/css/offcanvas.css" %}'  />
    <link rel="stylesheet" type="text/css" href='{% static "bootstrap/css/footer_down.css" %}'  />


    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">База ППР</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="#">Запланированные работы</a></li>
            <li><a href="#about">Журнал отклонений</a></li>
            <li><a href="#contact">Журнал предложений</a></li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <div class="starter-template">
        <h1>Разработка базы ппр</h1>
        <p class="lead">База планово-предупредительного ремонта оборудования</p>
      </div>

    </div><!-- /.container -->

  <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static 'bootstrap/js/offcanvas.js' %}"></script>

  </body>
</html>

src/templates/base_effect.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Наша ряба</title>

    <!-- Bootstrap -->
{% load i18n %}
{% load staticfiles %}

    <link rel="stylesheet" type="text/css" href='{% static "bootstrap/css/bootstrap.min.css" %}' />
    <link rel="stylesheet" type="text/css" href='{% static "bootstrap/css/offcanvas.css" %}'  />
    <link rel="stylesheet" type="text/css" href='{% static "bootstrap/css/footer_down.css" %}'  />
    <link rel="stylesheet" type="text/css" href='{% static "bootstrap/css/dashboard.css" %}'  />

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body><div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Главная </a>
          <a class="navbar-brand" href={% url "effect_log:effect_log_index" %}>{% trans "Журнал эффективности" %}</a>

        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          </ul>

<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
        <li><a href={% url "dashboard:dashboard_index" %}>{% trans "Личный кабинет" %}</a></li>
        <li><a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a></li>
    {% else %}
        <li><a href="{% url 'auth_login' %}">{% trans "Log in" %}</a></li>
    {% endif %}
</ul>
        </div>
      </div>
    </div>

<div class="col-sm-3 col-md-2 sidebar">

{% load category_widgets %}
{% menu_tag %}

</div>
<!-- MENU -->


    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h3 class="page-header">Журнал эффективности работы оборудования</h3>


<!-- content -->{% block content %} {% endblock %}

        </div>
      </div>
    </div>
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/offcanvas.js' %}"></script>

  </body>
</html>